---

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - fluent-plugin-record-demux.gemspec
    - test/**/*.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*.rb
    - lib/fluent/plugin/out_record_demux.rb

Metrics/MethodLength:
  Max: 25
  Exclude:
    - test/**/*.rb

Metrics/ParameterLists:
  Exclude: []

Style/Documentation:
  Enabled: false
